### ISSUE TITLE
cache error

### ISSUE THREAD

**Issue by 6lack-63ar** [N-John/mikrotik_hermes#6]
_
| |__   ___ _ __ _ __ ___   ___  ___   ___  ___ _ ____   _(_) ___ ___
| '_ \ / _ \ '__| '_ ` _ \ / _ \/ __| / __|/ _ \ '__\ \ / / |/ __/ _ \
| | | |  __/ |  | | | | | |  __/\__ \_\__ \  __/ |   \ V /| | (_|  __/
|_| |_|\___|_|  |_| |_| |_|\___||___(_)___/\___|_|    \_/ |_|\___\___|

HERMES SERVICE IS CREATED BY JOHN TO MANAGE MIKROTIK ISP SERVICES VIA HOTSPOT AND PPPoE.
To run this code, make sure you can connect to the router/server and to the sql server.
Make sure the "variables.txt" file has the appropriate data

DISCLAIMER:
BEFORE RUNNING, MAKE SURE YOU HAVE THE FOLLOWING
    sqlite3     -> used for sql database
    paramiko    -> used for ssh communication
    time        ->
    datetime    ->

OWNER: JOHN NJOROGE
GITHUB: https://github.com/N-John/mikrotik_hermes.git

LAST MODIFIED: 6-Feb-2024

[31-Mar-2024 09:33:52] HERMES WINGU SERVICE STARTUP

[31-Mar-2024 09:33:52] UPDATING CACHE...[####################
USER CACHE FAIL: no such table: account
cache failed
[31-Mar-2024 09:33:52] ERROR. SQL SERVER UNREACHABLE
PS C:\Users\okind\github\mikrotik_hermes>

after running the code  but the database is accessible

  from hermes.py   line  907 
            except Exception as e:
                print(f'{tme()}ERROR. SQL SERVER UNREACHABLE')
                log('ERROR. SQL SERVER UNREACHABLE')
                print(e)
                sys.exit() #EXIT PROGRAM

 the code and the new error after printing out the exception 

[31-Mar-2024 09:36:33] HERMES WINGU SERVICE STARTUP

[31-Mar-2024 09:36:33] UPDATING CACHE...[####################
USER CACHE FAIL: no such table: account
cache failed
[31-Mar-2024 09:36:33] ERROR. SQL SERVER UNREACHABLE
""""""""""no such table: account""""""""""
PS C:\Users\okind\github\mikrotik_hermes>

**Comment by N-John** [comment]
Are you using the latest pull? From your post, I can see that yours is "LAST MODIFIED: 6-Feb-2024" while the latest version is "LAST MODIFIED: 27-Mar-2024".
